-- MySQL Script generated by MySQL Workbench
-- Sat Apr 24 12:29:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Sport_Meeting_Management_System
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sport_Meeting_Management_System
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Sport_Meeting_Management_System`;
CREATE SCHEMA IF NOT EXISTS `Sport_Meeting_Management_System` DEFAULT CHARACTER SET utf8 ;
USE `Sport_Meeting_Management_System` ;

-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`College_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`College_rank` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`College_rank` (
  `College_score` INT NOT NULL,
  `College_ranking` INT NOT NULL,
  PRIMARY KEY (`College_score`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`College`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`College` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`College` (
  `College_name` VARCHAR(45) NOT NULL,
  `College_score` INT NOT NULL,
  `Manager` VARCHAR(45) NOT NULL,
  `Population` INT NOT NULL,
  PRIMARY KEY (`College_name`),
  CONSTRAINT `college_score`
    FOREIGN KEY (`College_score`)
    REFERENCES `Sport_Meeting_Management_System`.`College_rank` (`College_score`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `college_score_idx` ON `Sport_Meeting_Management_System`.`College` (`College_score` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Player` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Player` (
  `Player_id` INT UNSIGNED NOT NULL,
  `Player_name` VARCHAR(45) NOT NULL,
  `Gender` VARCHAR(45) NOT NULL,
  `College_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Player_id`),
  CONSTRAINT `fk_Player_College1`
    FOREIGN KEY (`College_name`)
    REFERENCES `Sport_Meeting_Management_System`.`College` (`College_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `College_name` ON `Sport_Meeting_Management_System`.`Player` (`College_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Volunteer_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Volunteer_name` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Volunteer_name` (
  `Volunteer_id` INT UNSIGNED NOT NULL,
  `Volunteer_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Volunteer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Org_comm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Org_comm` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Org_comm` (
  `Org_comm_id` INT UNSIGNED NOT NULL,
  `Org_comm_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Org_comm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Referee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Referee` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Referee` (
  `Referee_id` INT UNSIGNED NOT NULL,
  `Referee_name` VARCHAR(45) NOT NULL,
  `Salary` INT UNSIGNED NOT NULL,
  `Org_comm_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Referee_id`),
  CONSTRAINT `fk_Referee_Org Comm1`
    FOREIGN KEY (`Org_comm_id`)
    REFERENCES `Sport_Meeting_Management_System`.`Org_comm` (`Org_comm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Referee_Org Comm1_idx` ON `Sport_Meeting_Management_System`.`Referee` (`Org_comm_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Field_org`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Field_org` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Field_org` (
  `Field_name` VARCHAR(45) NOT NULL,
  `Org_comm_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Field_name`),
  CONSTRAINT `fk_Field_Org_comm_id`
    FOREIGN KEY (`Org_comm_id`)
    REFERENCES `Sport_Meeting_Management_System`.`Org_comm` (`Org_comm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Field_Org Comm1_idx` ON `Sport_Meeting_Management_System`.`Field_org` (`Org_comm_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `Field_name_UNIQUE` ON `Sport_Meeting_Management_System`.`Field_org` (`Field_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Event` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Event` (
  `Event_name` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(45) BINARY NOT NULL,
  `Round` VARCHAR(45) NOT NULL,
  `Starting_time` DATETIME NOT NULL,
  `Ending_time` DATETIME NOT NULL,
  `Field_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Event_name`, `Category`, `Round`),
  CONSTRAINT `fk_Event_Field1`
    FOREIGN KEY (`Field_name`)
    REFERENCES `Sport_Meeting_Management_System`.`Field_org` (`Field_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Event_Field` ON `Sport_Meeting_Management_System`.`Event` (`Field_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Event_Result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Event_Result` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Event_Result` (
  `Ranking` INT UNSIGNED NOT NULL,
  `Id` INT UNSIGNED NOT NULL,
  `Performance` VARCHAR(45) NULL,
  `Event_name` VARCHAR(45) NOT NULL,
  `Event_category` VARCHAR(45) BINARY NOT NULL,
  `Event_round` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`, `Event_name` , `Event_category` , `Event_round`),
  CONSTRAINT `fk_Event_Result_Event_name_category_round`
    FOREIGN KEY (`Event_name` , `Event_category` , `Event_round`)
    REFERENCES `Sport_Meeting_Management_System`.`Event` (`Event_name` , `Category` , `Round`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Event_Result_Event1_idx` ON `Sport_Meeting_Management_System`.`Event_Result` (`Event_name` ASC, `Event_category` ASC, `Event_round` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Event_has_Player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Event_has_Player` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Event_has_Player` (
  `Event_name` VARCHAR(45) NOT NULL,
  `Event_category` VARCHAR(45) BINARY NOT NULL,
  `Event_round` VARCHAR(45) NOT NULL,
  `Player_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Event_name`, `Event_category`, `Event_round`, `Player_id`),
  CONSTRAINT `fk_Event_has_Player_Event1`
    FOREIGN KEY (`Event_name` , `Event_category` , `Event_round`)
    REFERENCES `Sport_Meeting_Management_System`.`Event` (`Event_name` , `Category` , `Round`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_has_Player_Player1`
    FOREIGN KEY (`Player_id`)
    REFERENCES `Sport_Meeting_Management_System`.`Player` (`Player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Event_has_Player_Player1_idx` ON `Sport_Meeting_Management_System`.`Event_has_Player` (`Player_id` ASC) VISIBLE;

CREATE INDEX `fk_Event_has_Player_Event1_idx` ON `Sport_Meeting_Management_System`.`Event_has_Player` (`Event_name` ASC, `Event_category` ASC, `Event_round` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Event_has_Referee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Event_has_Referee` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Event_has_Referee` (
  `Event_name` VARCHAR(45) NOT NULL,
  `Event_category` VARCHAR(45) BINARY NOT NULL,
  `Event_round` VARCHAR(45) NOT NULL,
  `Referee_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Event_name`, `Event_category`, `Event_round`, `Referee_id`),
  CONSTRAINT `fk_Event_has_Referee_Event1`
    FOREIGN KEY (`Event_name` , `Event_category` , `Event_round`)
    REFERENCES `Sport_Meeting_Management_System`.`Event` (`Event_name` , `Category` , `Round`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_has_Referee_Referee1`
    FOREIGN KEY (`Referee_id`)
    REFERENCES `Sport_Meeting_Management_System`.`Referee` (`Referee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Event_has_Referee_Referee1_idx` ON `Sport_Meeting_Management_System`.`Event_has_Referee` (`Referee_id` ASC) VISIBLE;

CREATE INDEX `fk_Event_has_Referee_Event1_idx` ON `Sport_Meeting_Management_System`.`Event_has_Referee` (`Event_name` ASC, `Event_category` ASC, `Event_round` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Volunteer_has_Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Volunteer_has_Event` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Volunteer_has_Event` (
  `Volunteer_id` INT UNSIGNED NOT NULL,
  `Event_name` VARCHAR(45) NOT NULL,
  `Event_category` VARCHAR(45) BINARY NOT NULL,
  `Event_round` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Volunteer_id`, `Event_name`, `Event_category`, `Event_round`),
  CONSTRAINT `fk_Volunteer_has_Event_Volunteer1`
    FOREIGN KEY (`Volunteer_id`)
    REFERENCES `Sport_Meeting_Management_System`.`Volunteer_name` (`Volunteer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Volunteer_has_Event_Event1`
    FOREIGN KEY (`Event_name` , `Event_category` , `Event_round`)
    REFERENCES `Sport_Meeting_Management_System`.`Event` (`Event_name` , `Category` , `Round`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Volunteer_has_Event_Event1_idx` ON `Sport_Meeting_Management_System`.`Volunteer_has_Event` (`Event_name` ASC, `Event_category` ASC, `Event_round` ASC) VISIBLE;

CREATE INDEX `fk_Volunteer_has_Event_Volunteer1_idx` ON `Sport_Meeting_Management_System`.`Volunteer_has_Event` (`Volunteer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Volunteer_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Volunteer_time` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Volunteer_time` (
  `Volunteer_id` INT UNSIGNED NOT NULL,
  `Available_starting_time` DATETIME NOT NULL,
  `Available_ending_time` DATETIME NOT NULL,
  PRIMARY KEY (`Volunteer_id`, `Available_starting_time`, `Available_ending_time`),
  CONSTRAINT `volunteer_id`
    FOREIGN KEY (`Volunteer_id`)
    REFERENCES `Sport_Meeting_Management_System`.`Volunteer_name` (`Volunteer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sport_Meeting_Management_System`.`Field_time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sport_Meeting_Management_System`.`Field_time` ;

CREATE TABLE IF NOT EXISTS `Sport_Meeting_Management_System`.`Field_time` (
  `Available_starting_time` DATETIME NOT NULL,
  `Available_ending_time` DATETIME NOT NULL,
  `Field_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Field_name`, `Available_ending_time`, `Available_starting_time`),
  CONSTRAINT `Field_name`
    FOREIGN KEY (`Field_name`)
    REFERENCES `Sport_Meeting_Management_System`.`Field_org` (`Field_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
